# Generated by Django 2.1.7 on 2019-03-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=250)),
                ('date', models.DateTimeField()),
                ('vote_count', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='product/')),
                ('icon', models.ImageField(upload_to='product/')),
            ],
        ),
    ]
